site_name: Casa Rosa
site_description: Informationen für unsere Gäste
site_url: https://yannstricker.github.io/Casa-Rosa/

theme:
  name: material
  language: de
  custom_dir: docs/overrides
  palette:
    primary: blue
    accent: light blue

plugins:
  - search
  - glightbox
  
nav:
  - Startseite: index.md
  - Ankunft & Abreise: ankunft-abreise.md
  - Infos zur Wohnung: wohnung.md
  - Ausflugsideen & Tipps: ausfluege-tipps.md

markdown_extensions:
  - admonition
  - tables
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - toc:
      permalink: true